### PR TITLE
Added hacktoberfest poster

### PR DESCRIPTION
**Pull request by shikharish**

### CODE REVIEW

**Review by harshkhandeparkar — DISMISSED** [review]

**Comment by harshkhandeparkar** [comment]
Do we have the source files/links for these poster? If yes, it would be better if you add them in a markdown file in the same folder.

**Comment by shikharish** [comment]
> Do we have the source files/links for these poster? If yes, it would be better if you add them in a markdown file in the same folder.

Added.

**Review by harshkhandeparkar — CHANGES_REQUESTED** [review]
image
Please give view permission to everyone with the link :)

**Comment by shikharish** [comment]
> image Please give view permission to everyone with the link :)

Done

**Review by harshkhandeparkar — APPROVED** [review]

**Pull request merged**
